version: '3.3'

services:
  backend:
    build: ./backend
    volumes:
      - ./uploads:/app/uploads  # Mounts `./uploads` (host) to `/app/uploads` (container)
      - ./screenshots:/app/screenshots  # Mounts `./uploads` (host) to `/app/uploads` (container)
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
