version: '3.3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
