version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'"

  backend:
    build: ./backend
    volumes:
      - ./uploads:/app/uploads  # Mounts `./uploads` (host) to `/app/uploads` (container)
      - ./screenshots:/app/screenshots  # Mounts `./uploads` (host) to `/app/uploads` (container)
    expose:
      - "8000"
    env_file:
      - .env
    restart: always

  frontend:
    build: ./frontend
    expose:
      - "3000"
    depends_on:
      - backend
    restart: always
