name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - v*

jobs:
  linter:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install black
      run: pip install black==24.4.2

    - name: Check black format 
      run:  black --check --diff .

  tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install requirements
      run: pip install -r backend/requirements.txt

    - name: Run tests
      run: python -m pytest backend/ -vv
